[package]
name = "rust-noisegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorgrad = "0.6.2"
image = "0.24.4"
itertools = "0.10.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
